// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxioobiygfqjeswcfuod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4aW9vYml5Z2ZxamVzd2NmdW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTY1MTUsImV4cCI6MjA2NDAzMjUxNX0.gATobRRpka5r6IW4fkx0bkRp9a51iOuG7QO1pGxgE2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);